[project]
name = "mne-opm"
version = "0.1.0"
description = "OPM preprocessing and analysis tools built on MNE-Python and MNE-BIDS-PIPELINE"
readme = "README.md"
requires-python = "~=3.13.0"
dependencies = [
    "dcm2niix>=1.0.20250506",
    "ipykernel>=7.1.0",
    "mne",
    "mne-bids",
    "mne-bids-pipeline",
    "mne-qt-browser>=0.7.4",
    "osl-ephys",
    "pyopengl>=3.1.10",
    "pyqt5>=5.15.11",
    "pyvista>=0.46.4",
    "trame>=3.12.0",
    "vtk>=9.5.2",
]

[tool.uv.sources]
mne-bids = { git = "https://github.com/harrisonritz/mne-bids.git", rev = "mne-opm" }
mne-bids-pipeline = { git = "https://github.com/harrisonritz/mne-bids-pipeline.git", rev = "mne-opm" }
osl-ephys = { git = "https://github.com/harrisonritz/osl-ephys.git" }
mne = { git = "https://github.com/harrisonritz/mne-python.git", branch = "mne-opm" }

[tool.uv]
override-dependencies = [
    "mne @ git+https://github.com/harrisonritz/mne-python.git@mne-opm"
]
